# Generated by Django 3.2 on 2021-05-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210517_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
