# Generated by Django 3.0.6 on 2020-06-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articls',
            new_name='Articles',
        ),
    ]
