# Generated by Django 3.0.6 on 2020-08-02 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200621_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته بندی مقاله')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='chiz',
            options={'verbose_name': 'نمونه', 'verbose_name_plural': 'نمونه ها'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(verbose_name=' شرح مقاله'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشرشده')], max_length=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thamnail',
            field=models.ImageField(upload_to='images', verbose_name='عکس '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان '),
        ),
        migrations.AlterField(
            model_name='articles',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ ویرایش'),
        ),
    ]
