# Generated by Django 3.0.6 on 2020-08-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200803_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
